language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby
  - ree
script: "bundle exec rake"
before_install:
 - sudo apt-get update
 - sudo apt-get install idn
notifications:
  email:
    recipients:
      - bobaman@google.com
      - sbazyl@google.com
    on_success: change
    on_failure: change
