language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-2
  - jruby-19mode
script: "bundle exec rake spec:all"
before_install:
 - sudo apt-get update
 - sudo apt-get install idn
notifications:
  email:
    recipients:
      - sbazyl@google.com
    on_success: change
    on_failure: change
